### ISSUE TITLE
Multi-lang Component Roadmap

### ISSUE THREAD

**Issue by ajhool** [pulumi/pulumi-aws-quickstart-vpc#15]
Component Roadmap

- [x] Merge feat/vpc-flow logs PR
- [x] Parameters
  - [x] VPC Name -human friendly ("eg. Pulumi Vpc")
    - [ ] Optional
    - [ ] Parameterized
    - [ ] Default
  - [x] Namespace - used for resource names where spaces aren't allowed (eg. pulumi-vpc)
    - [ ] Is this needed?
    - [ ] Optional
    - [ ] Parameterized
    - [ ] Default
  - [x] Default Instance Tenancy: "default" | "dedicated"
    - [ ] Optional
    - [ ] Parameterized
    - [ ] Default
  - [x] Flow Logs Config
    - [ ] Optional
    - [ ] Parameterized
    - [ ] Default
  - [x] VPC Cidr Block
    - [ ] Optional
    - [ ] Parameterized
    - [ ] Default
  - [x] Availability Zone Configs
    - [ ] Array with elements:
      - [ ] publicSubnetName:   "Pulumi Public Subnet 1",
      - [ ] publicSubnetCidr:   "10.0.5.0/24",
      - [ ] availabilityZone:   "us-east-1a"
      - [ ] privateSubnetA
        - [x] Name
        - [x] CIDR
      - [x] privateSubnetB:
        - [x] Name
        - [x] CIDR
- [x] Code Sweep
  - [x] Improve function names
  - [x] Improve code layout
  - [x] Should "Tags" be passed through?
  - [x] Add comments, remove old comments, etc. 
- [x] Test Deployments
  - [x] Public Subnet Only
  - [x] Private Subnet Only
  - [x] 2 Private Subnets
  - [x] Public Subnet
  - [x] Public Subnet + 2 Private Subnets
- [x] Documentation
  - [x] Basic README pointing to AWS Quickstart Guide
  - [x] Example Usage (maybe use the Test Deployments above)
